car/urls.py
# car/urls.py
from django.conf.urls import url

from .import views

urlpatterns = [

    url(r'^dashboard/$', views.not_authorized, name='not_authorized'),
    url(r'^(?P<car_id>[0-9]+)/$', views.car_detail, name='car_detail'),
    url(r'^car_maker/(?P<maker_id>[0-9]+)/$', views.car_maker_detail, name='maker_detail'),
    url(r'^car_list/$', views.car_list, name='car_list'),
    url(r'^car_maker_list/$', views.car_maker_list, name='maker_list'),
]

car_project2/urls.py
# Project URL
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from car.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^user_profile/', include('core_user.urls', namespace="user_profile")),
    url(r'^vehicle/', include('car.urls', namespace='vehicle')),

    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'registration/logged_out.html'}, name='logout'),
    url(r'^admin/', admin.site.urls),
]

car/models.py
from django.db import models


class CarMaker(models.Model):
    car_maker = models.CharField(max_length=65)

    def __str__(self):
        return self.car_maker

    class Meta:
        permissions = (('Can view car_maker', 'can_view_car_maker'),)


class Car(models.Model):
    car_name = models.CharField(max_length=65)
    car_maker = models.ForeignKey(CarMaker)
    year = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.car_name

car/forms.py
from django.forms import ModelForm

from .models import Car, CarMaker


class CarForm(ModelForm):

    class Meta:
        model = Car
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class CarMakerForm(ModelForm):

    class Meta:
        model = CarMaker
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

car/views.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views import View

from .models import Car, CarMaker


class IndexView(View):
    def get(self, request):
        return render(request, 'car/index.html', {'section': 'index'})


def not_authorized(request):
    return render(request, 'car/not_authorized.html')


# @permission_required('car.can_view_car_maker', 'vehicle:not_authorized')
def car_detail(request, car_id):
    car = get_object_or_404(Car, id=car_id)
    # import pdb; pdb.set_trace()
    return render(request, 'car/car_detail.html', {'car': car})


def car_maker_detail(request, maker_id):
    car_maker = get_object_or_404(CarMaker, id=maker_id)
    return render(request, 'car/car_maker_detail.html', {'car_maker': car_maker})


def car_list(request):
    cars = Car.objects.all().order_by('car_name')
    paginator = Paginator(cars, 25)
    page = request.GET.get('page')
    try:
        cars = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        cars = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        cars = paginator.page(paginator.num_pages)

    return render(request, 'car/car_list.html',
                  {'cars': cars}
                  )


def car_maker_list(request):
    car_makers = CarMaker.objects.all().order_by('car_maker')
    paginator = Paginator(car_makers, 25)
    page = request.GET.get('page')
    try:
        car_makers = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        car_makers = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        car_makers = paginator.page(paginator.num_pages)

    return render(request, 'car/car_maker_list.html',
                  {'car_makers': car_makers}
                  )

templates/car/car_detail.html
{% extends base_html %}

{% block title %}Car Detail{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-4">
    <div class="container">
      <h2>Car Detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row">Vehicle Name:</th>
            <td>{{ car.car_name }}</td>
          </tr>
          <tr>
            <th scope="row">Vehicle Maker</th>
            <td>{{ car.car_maker }}</td>
          </tr>
          <tr>
            <th scope="row">Year:</th>
            <td>{{ car.year }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-lg-8 visible-lg">
  </div>
</div>
{% endblock %}

templates/car/car_list.html
{% extends "base.html" %}

{% block title %}Car List{% endblock %}

{% block content %}
<div class="border row">
  <div class="col-sm-2"></div>
  <div class="col-sm-6">
  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>#</th>
        <th>vehicle</th>
        <th>vehicle Maker</th>
        <th>Year</th>
      </tr>
    </thead>
    <tbody>
      {% for car in cars %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url "vehicle:car_detail" car_id=car.id %}">{{ car.car_name }}</a></td>
        <td>{{ car.car_maker }}</td>
        <td>{{ car.year }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="col-sm-2"></div>
</div>


<div class="pagination">
    <span class="step-links">
        {% if cars.has_previous %}
            <a href="?page={{ cars.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ cars.number }} of {{ cars.paginator.num_pages }}.
        </span>

        {% if cars.has_next %}
            <a href="?page={{ cars.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/car/car_maker_detail.html
{% extends "base.html" %}

{% block title %}Car Detail{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-4">
    <div class="container">
      <h2>Car Maker Detail</h2>
      <h2>{{ car_maker }}</h2>
      <h2>Todo Add cars made by maker<h2>
    </div>
  </div>
  <div class="col-lg-8 visible-lg">
  </div>
</div>
{% endblock %}

templates/car/car_maker_list.html
{% extends "base.html" %}

{% block title %}Car Makers{% endblock %}

{% block content %}
<div class="border row">
  <div class="col-sm-2">.col-sm-4</div>
  <div class="col-sm-6">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>#</th>
        <th>Car Makers</th>
        </tr>
      </thead>
      <tbody>
        {% for make in car_makers %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td><a href="{% url "vehicle:maker_detail" maker_id=make.id %}">{{ make }}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col-sm-2">.col-sm-4</div>

</div>
<div class="pagination">
  <span class="step-links">
    {% if car_makers.has_previous %}
      <a href="?page={{ car_makers.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ car_makers.number }} of {{ car_makers.paginator.num_pages }}.
    </span>

    {% if car_makers.has_next %}
      <a href="?page={{ car_makers.next_page_number }}">next</a>
    {% endif %}
  </span>
</div>
{% endblock %}

templates/car/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  <div id="col-sm-12" class="pageWrapper">
    <h1>Dashboard Management  --- WIP</h1>
  </div>
{% endblock %}

templates/car/index.html
{% extends "base.html" %}

{% block title %}Car Project{% endblock %}

{% block content %}
  <div id="col-sm-12" class="pageWrapper">
    <h1>Car Project</h1>
  </div>
{% endblock %}

templates/car/not_authorized.html
{% extends "base.html" %}

{% block title %}No Authority{% endblock %}

{% block content %}
  <div id="col-sm-12" class="pageWrapper">
    <h1>You are not authorized to view this page</h1>
  </div>
{% endblock %}

templates/car/vehicle_maker.html
{% extends "base.html" %}

{% block title %}Car Maker Detail{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-4">
  <span class="pull-right"><h1>Car:</h1></span>
  </div>
  <div class="col-sm-8">
  <h1>{{ maker }}</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <div class="container">
      <h2>Car Maker Detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row">Car Maker:</th>
            <td>{{ maker.car_maker }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-lg-8 visible-lg">
  </div>
</div>
{% endblock %}